// Copyright 2019 Job Stoit. All rights reserved.

// gqb is made for generating a query builder.
//
// The gqb command takes the path to the db.yml as argument
//
// The command takes the following flags as arguments
//   -migrate 		Specifies the output for a generated sql migration
//
//   -db                Directly inserts the configured structure into the database
//                      using the DB_DRIVER and DB_CONNECTION_STRING enviroment
//                      variables or the flags for this mode
//
//   -dvr               Set the driver for the db flag
//
//   -cs                Sets the connection string for the db flag
//
//   -model             Writes the configuration to NiseVoid/qb model(s) takes
//                      the output file(s) as argument
//
//   -pkg               Used by the model flag, sets the package name of the
//                      model file(s)
//
package main

import (
	"flag"
	"io/ioutil"
)

// Program flags
var (
	model = flag.String(`model`, ``, `Writes the configuration to git.ultraware.nl/NiseVoid/qb models and takes the target output as argument`)
)

func main() {
	flag.Parse()
	target := `db.yml`
	if flag.Arg(0) != `` {
		target = flag.Arg(0)
	}

	bitz, err := ioutil.ReadFile(target)
	catch(err)

	mdl := ReadConfig(bitz)

	if *model != `` {
		file := create(*model,
			`// This file is generated by github.com/jobstoit/gqb, PLEASE DO NOT EDIT!

package models

import "git.ultraware.nl/NiseVoid/qb"

`,
		)
		CreateQbModel(mdl, file)
		defer file.Close()
	}
}
