// Copyright 2019 Job Stoit. All rights reserved.

package main

import (
	"flag"
	"io/ioutil"
)

// Program flags
var (
	model = flag.String(`model`, ``, `Writes the configuration to git.ultraware.nl/NiseVoid/qb models and takes the target output as argument`)
)

func main() {
	flag.Parse()
	target := `db.yml`
	if flag.Arg(0) != `` {
		target = flag.Arg(0)
	}

	bitz, err := ioutil.ReadFile(target)
	catch(err)

	mdl := ReadConfig(bitz)

	if *model != `` {
		file := create(*model,
			`// This file is generated by github.com/jobstoit/gqb, PLEASE DO NOT EDIT!

package models

import "git.ultraware.nl/NiseVoid/qb"

`,
		)
		CreateQbModel(mdl, file)
		defer file.Close()
	}
}
